import './globals.css'
import GoogleAnalytics from './GoogleAnalytics'

export const metadata = {
  title: 'Calel Sprumont',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <head></head>
      <GoogleAnalytics GA_TRACKING_ID='G-YXQG2XJR7T'/>
      <body>{children}</body>
    </html>
  )
}

